### ISSUE TITLE
[Llama 3B] Support for attention block (no KV cache)

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-forge-fe#123]
## Summary
For the full Llama 3B model bringup, we want to test the main standalone blocks before running full model e2e. One of those blocks is the attention module.

## Details
For initial Llama 3B support, we're not focusing on support with KV cache, but rather we'll try to push it by re-computing key and value tensors for each token during every run. This is not optimal, but once we get Llama 3B up and running we'll focus on KV cache support as well. 

Therefore, this issue should prove that Llama 3B self-attention standalone is working successfully. The initial test setup is located here:
```py
pytest -svv forge/test/mlir/llama/tests/test_llama_self_attn.py
```

_Note: Have in mind that depending on new findings, this test can be expanded to better encapsulate Llama 3B self-attention mechanism_

**Comment by nvukobratTT** [comment]
Moving KV cache support as P1 once we get functional model e2e working

**Comment by nvukobratTT** [comment]
@chandrasekaranpradeep plese check this one as well as it's related to reduce mean as well :)

**Comment by dgolubovicTT** [comment]
Sorry, which blocker was removed? What was blocking what?

**Comment by nvukobratTT** [comment]
> Sorry, which blocker was removed? What was blocking what?

Sorry for not providing enough context :)) In sum, blocker issues for this model was bug in `ttnn.mean` op. Now that MLIR is successfully uplifted with the required changes, we should double-check if this issue is successfully solved for Llama 3B self-attention block. 

Ofc, there is a potential that this section is blocked with other upcoming issues, but that's fine. In that case, just comment the details here, and link the blocking issues into `Blocker` field of this issue :))

**Comment by dgolubovicTT** [comment]
Llama 3B Attention is currently blocked on [metal issue](https://github.com/tenstorrent/tt-metal/issues/13667). Tile padding along concatenated dim is not supported yet. This concatenate is part of rotary embeddings. When I turn off rotary embeddings in source code of the Llama Attention attention fully passes. So we are blocked by this concatenate issue.

**Comment by dgolubovicTT** [comment]
Attention block works since this tt-mlir uplift [PR](https://github.com/tenstorrent/tt-forge-fe/pull/824
)
