### ISSUE TITLE
[Llama 3B] Support for RMS normalization block

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-forge-fe#125]

**Comment by nvukobratTT** [comment]
@chandrasekaranpradeep this one is unblocked as well. Can you check if there are other related issues tied to the RMS norm?

**Comment by chandrasekaranpradeep** [comment]
@nvukobratTT I have tested the RMS normalization test cases (i.e [forge/test/mlir/llama/tests/test_llama_rotary_emb.py](https://github.com/tenstorrent/tt-forge-fe/blob/3817b9b2e559cb97497e035c7cf62e69bac455b3/forge/test/mlir/llama/tests/test_llama_rotary_emb.py)). It works fine.
Log:
[rms_norm.log](https://github.com/user-attachments/files/17165192/rms_norm.log)

Can we create a PR for running in CI?

**Comment by nvukobratTT** [comment]
> @nvukobratTT I have tested the RMS normalization test cases (i.e [forge/test/mlir/llama/tests/test_llama_rotary_emb.py](https://github.com/tenstorrent/tt-forge-fe/blob/3817b9b2e559cb97497e035c7cf62e69bac455b3/forge/test/mlir/llama/tests/test_llama_rotary_emb.py)). It works fine. Log: [rms_norm.log](https://github.com/user-attachments/files/17165192/rms_norm.log)
> 
> Can we create a PR for running in CI?

If this test is passing, let's add it to the CI and ensure that it's supported :))

**Comment by chandrasekaranpradeep** [comment]
@nvukobratTT Created a PR for RMS normalization -  https://github.com/tenstorrent/tt-forge-fe/pull/349

**Comment by chandrasekaranpradeep** [comment]
Llama 3b RMS normalization test  is uplifted into main (PR: https://github.com/tenstorrent/tt-forge-fe/pull/349). so closing the issue
