### ISSUE TITLE
[Emit] When hitting unsupported on on MLIR, print all unsupported ops, not only the first one. 

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-forge-fe#141]
Best case is to print ops before lowering to MLIR. However, the model can often fail long before. Therefore, it'll be good to have a mechanism to print the same list of required ops at different compile depths.

Also, info that is of interest:
1. List of unique op types (e.g. matmul, add, etc)
2. List of unique op type configurations (input shapes, attributes, etc.)

As a first step, let's push this change on Buda stack, and gather details over there. Then, we can cherry-pick the logic onto Forge as well and continue with information gathering while Forge models are being analyzed.

**Comment by chandrasekaranpradeep** [comment]
Buda PR: https://yyz-gitlab.local.tenstorrent.com/tenstorrent/pybuda/-/merge_requests/2331
