### ISSUE TITLE
[Llama 3B] Support for rotary embedings

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-forge-fe#165]

**Comment by nvukobratTT** [comment]
There are some dynamic shapes on the TVM level when the pure block is extracted.

**Comment by chandrasekaranpradeep** [comment]
- Update the llama Rotary embedding test to avoid generation of  dynamic shapes from TVM pytorch frontend conversion (PR : https://github.com/tenstorrent/tt-forge-fe/pull/330) 

- `Unsupported operation for lowering from TTForge to TTIR: sparse_matmul` error will be thrown while lowering to TTIR, which can be resolved, once the [Adding decompose for Indexing op using Transpose and Matmul](https://github.com/tenstorrent/tt-forge-fe/pull/310) PR is merged

- Raised Issue for the concat op - [#795](https://github.com/tenstorrent/tt-mlir/issues/795)

**Comment by dgolubovicTT** [comment]
Llama rotary embeddings is blocked in runtime by [this tt-metal issue](https://github.com/tenstorrent/tt-metal/issues/13667).

**Comment by dgolubovicTT** [comment]
Rotary embeddings are now supported since this mlir uplit [PR](https://github.com/tenstorrent/tt-forge-fe/pull/824)
