### ISSUE TITLE
Add a getting started example

### ISSUE THREAD

**Issue by staylorTT** [tenstorrent/tt-forge-fe#217]
Can we add a brief example on how to get started with the FFE? Maybe a smoke test ? https://github.com/tenstorrent/tt-forge-fe/blob/main/docs/src/getting-started.md

**Comment by nvukobratTT** [comment]
We added Testing page, which is good getting started section:
- https://docs.tenstorrent.com/tt-forge-fe/test.html

For now, this section is good enough to cover it. However, we should think in a future how to enhance documentation even further.
