### ISSUE TITLE
Rename PyBuda/Buda in Reportify (create new buda_track branch)

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-forge-fe#246]
For Buda, create a buda_track branch. And for FFE use new main.

**Comment by chandrasekaranpradeep** [comment]
Created a MR for tt-forge-fe: [https://yyz-gitlab.local.tenstorrent.com/tenstorrent/reportify/-/merge_requests/2](https://yyz-gitlab.local.tenstorrent.com/tenstorrent/reportify/-/merge_requests/2)
Created a buda_track branch for Pybuda: [https://yyz-gitlab.local.tenstorrent.com/tenstorrent/reportify/-/tree/buda_track?ref_type=heads](https://yyz-gitlab.local.tenstorrent.com/tenstorrent/reportify/-/tree/buda_track?ref_type=heads)
