### ISSUE TITLE
TTIR Matmul requires both inputs have the same rank (blocking resnet)

### ISSUE THREAD

**Issue by LPanosTT** [tenstorrent/tt-forge-fe#287]
Seeing:
```
error: 'ttir.matmul' op Input A and B must have the same rank
```

When compiling the resnet_tf model. The matmul at the end of the model has a different rank for the input and weight. The branch with the test is: https://github.com/tenstorrent/tt-forge-fe/tree/lpanos/resnet_tf_test

Command to run test: `pytest forge/test/mlir/resnet/test_resnet_inference_tf.py`

@nvukobratTT Any solution ideas? I can think of one - unsqueeze all ops and inputs to 4 dimensions before lowering to MLIR.

**Comment by nvukobratTT** [comment]
@LPanosTT doing unsqueeze can solve the issue, however I think we should be able to model this and support it on the MLIR level. More precisely, there will be cases when the tensor rank is >4. As many models have cases like this one, I don't think increasing default rank each time is valid. 

Therefore, I have two suggestions depending on where we agree this should be handled:
1. Add pass on FFE that will match inputs to be on same rank (doing ether squeeze or unsqueeze)
2. Model this behavior on MLIR level:
    1. Simply forwarding matmul as is (no rank change on inputs) if ttnn is expected to support it
    2. Manipulate tensor ranks for all ops as separate pass on MLIR level

@sdjordjevicTT any thoughts on MLIR level? If you think this is Q for wider audience, we can bring it up on #uhuru channel as well.

**Comment by nvukobratTT** [comment]
@sdjordjevicTT As per our discussion over Slack, the conclusion seems to be that we should support any rank tensor on TTIR to map what is expected by TTNN/Metal. If you agree, @LPanosTT can probably create an issue on the MLIR repo as well with TTIR for easier repro :))

Also, if we create this issue on MLIR level, I think we can close this one and keep track on MLIR issue :)) Let me know your thoughts

**Comment by LPanosTT** [comment]
> If you agree, @LPanosTT can probably create an issue on the MLIR repo as well with TTIR for easier repro :))

Yeah, let's do that.

**Comment by LPanosTT** [comment]
Created here https://github.com/tenstorrent/tt-mlir/issues/717
