### ISSUE TITLE
BUG REPORT: Test for PyTorch binary op SUB

### ISSUE THREAD

**Issue by kmilanovicTT** [tenstorrent/tt-forge-fe#288]
### Description
When testing op Sub in inference mode with PyTorch models, tests are failing differently when they are run with one model(operand source) or with all models(operand sources) at once.
Test summary when run with one model:  36 failed, 39 passed, 2 warnings
Test summary when run with all models:  115 failed, 110 passed, 2 warnings - there are 3 models so expected number of failed tests is 108, not 115.

There are two error messages that occurs (they depend on witch shape for input tensor are used in test):
1. E       RuntimeError: Generated MLIR module failed verification.
2. E       RuntimeError: TT_THROW @ /home/kmilanovic/src/ttforge/tt-forge-fe/third_party/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_device_operation.cpp:46: tt::exception
   E       ttnn::operations::binary::BinaryDeviceOperation: unsupported broadcast

### Reproduce
Tune test 'test_pytorch_eltwise_binary_ops_per_test_plan' to work only with operator Sub/Substract and wth only 1 model or 3 models, depending on witch case you want to reproduce (ModelFromAnotherOp, ModelFromHost, ModelFromDramQueue).
Then run command:
pytest -svv forge/test/operators_pytorch/eltwise_binary/test_pytorch_binary.py::test_pytorch_eltwise_binary_ops_per_test_plan --no-skips --runxfail

**Comment by nvukobratTT** [comment]
Is it possible to run just a small subset you mentioned? The one when depending on group vs single test run produces different results.

**Comment by kmilanovicTT** [comment]
It was possible but after rebase on latest main, operator SUB doesn't produce these errors anymore. Only bug there is, is described in ticket: [#290](https://github.com/tenstorrent/tt-forge-fe/issues/290)
