### ISSUE TITLE
[Ops] Support for Max Pool 2D op (ttnn.max_pool2d)

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-forge-fe#291]

**Comment by LPanosTT** [comment]
@nvukobratTT Updating to the latest MLIR causes all maxpool2d tests to fail. Most of them failing because of the throw on line 125 of `third_party/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/operations/core/to_layout/to_layout_op.cpp`

**Comment by nsmithtt** [comment]
> @nsmithtt @nvukobratTT Updating to the latest MLIR causes all maxpool2d tests to fail. Most of them failing because of the throw on line 125 of `third_party/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/operations/core/to_layout/to_layout_op.cpp`
> 
> The ones that don't fail here have garbage output.

Which memory config is the one at fault here? The one that's coming from the calculate parallel config?

**Comment by LPanosTT** [comment]
> Which memory config is the one at fault here? The one that's coming from the calculate parallel config?

This is without my pre-shading hack. The data is correct after the maxpool op in all cases. The failure happens on the ToLayout call at the end of the model. And when the TT_THROW isn't hit, the data given to host is garbage.

As for the garbage output, I'm still not certain if its the ToLayout at the end, or the reshape inserted on the maxpool output that causes that.

**Comment by nsmithtt** [comment]
> > Which memory config is the one at fault here? The one that's coming from the calculate parallel config?
> 
> This is without my pre-shading hack. The data is correct after the maxpool op in all cases. The failure happens on the ToLayout call at the end of the model. And when the TT_THROW isn't hit, the data given to host is garbage.
> 
> As for the garbage output, I'm still not certain if its the ToLayout at the end, or the reshape inserted on the maxpool output that causes that.

Ok, let us know what you find.

**Comment by nvukobratTT** [comment]
> > Which memory config is the one at fault here? The one that's coming from the calculate parallel config?
> 
> This is without my pre-shading hack. The data is correct after the maxpool op in all cases. The failure happens on the ToLayout call at the end of the model. And when the TT_THROW isn't hit, the data given to host is garbage.
> 
> As for the garbage output, I'm still not certain if its the ToLayout at the end, or the reshape inserted on the maxpool output that causes that.

Yup, let's gather more details. Once we get a better understanding of what's happening, we can include someone from the MLIR team as well. 

@LPanosTT with new uplift, did you saw some more drastic changes coming between previous and current MLIR version you're referencing?
