### ISSUE TITLE
Implement slice op end to end.

### ISSUE THREAD

**Issue by dgolubovicTT** [tenstorrent/tt-forge-fe#299]
Currently, we can't lower slice op to mlir. We need this op for indexing when stride is 1. In general, indexing is done by matrix multiplication, but when stride is 1 it is ideal to use some kind of select.

**Comment by dgolubovicTT** [comment]
@nvukobratTT fyi, we can discuss the priority.

**Comment by nvukobratTT** [comment]
This makes sense, no need for matmul + transpose(s) if we have stride 1. From what I see, ttnn doesn't have some sophisticated select/slice ops. 

Let's chat around this one, and try to push it a bit further if we hit a model with it. In sum, indexing ops are probably a bit problematic to implement on tt-metal level. For now, we can sort this out using matmuls, but for further enhancement we'll for sure need more optimal approach.

**Comment by dgolubovicTT** [comment]
On metal they have slice op that does the same thing as select. Takes some continuous subtensor (defined by start and end indices on each dimension). So the only question is this op covered well on metal side. We will know that when we start using it. I suggest we try implementing it end to end on forge-mlir side and start using it. In lama we already have bunch of indexing with stride 1, so this will have an impact.

**Comment by dgolubovicTT** [comment]
Currently, this is just an optimization. LLama indexings are not that big, so they all work with matmul. So this is not a blocker...

**Comment by nvukobratTT** [comment]
Great, thanks @dgolubovicTT! 

@sdjordjevicTT This is probably P2, but it'll be nice to have it, as we can simplify a good number of cases for the indexing ops. @dgolubovicTT once you create issues for slice support on MLIR, please link it in this issue as "Blocker" field, so we can easily track it :))

**Comment by sdjordjevicTT** [comment]
I will close this item, as we decomposed indexing op in ttmlir.
