### ISSUE TITLE
Eltwise Binary tests don't truly pass.

### ISSUE THREAD

**Issue by LPanosTT** [tenstorrent/tt-forge-fe#302]
Add, subtract, and multiply all do not pass.

The assertion at the end of these tests is:
```
assert [compare_with_golden_pcc(golden=fo, calculated=co, pcc=0.99) for fo, co in zip(fw_out, co_out)]
```

However, any list of size > 0 will evaluate to true: 
```
>>> bool([False])
True
```

What we want to assert for these tests is 
```
assert all([compare_with_golden_pcc(golden=fo, calculated=co, pcc=0.99) for fo, co in zip(fw_out, co_out)])
```

Which ensure all list elements are `True`

From debugging, it looks like only the first row of the output is valid data, the rest are zeros.

CC: @nvukobratTT

**Comment by nvukobratTT** [comment]
Thanks for the notice, we should update this for all tests we're currently running.. 

I'll have one more eng from MCW coming to the Forge in a few days, so this looks like a good issues for a starter :))

**Comment by nvukobratTT** [comment]
Ofc, let me know if you would like to take a look beforehand :))

**Comment by LPanosTT** [comment]
> Ofc, let me know if you would like to take a look beforehand :))

Yeah I’m taking a look right now, it seems like this did work recently, bisecting…

**Comment by LPanosTT** [comment]
@nvukobratTT I'm not so sure what the issue was. Uplifting to the latest MLIR has fixed the issue though. It may have been entirely my fault and I had edited something on my branch without remembering.

**Comment by LPanosTT** [comment]
Merged
