### ISSUE TITLE
Unsupported operation for lowering from TTForge to TTIR: pad_tile

### ISSUE THREAD

**Issue by kamalrajkannan78** [tenstorrent/tt-forge-fe#497]
## Description

-  Unsupported operation for lowering from TTForge to TTIR: pad_tile on Forge inference 

## Reproduce

```
git checkout kkannan/forge_model_issues
git submodule update --recursive
export BACKEND_ARCH_NAME=wormhole_b0 ARCH_NAME=wormhole_b0 PYBUDA_FORCE_EMULATE_HARVESTED=1 
pytest forge/test/model_demos/high_prio/nlp/pytorch/test_llama3.py::test_llama3_sequence_classification[no_device-meta-llama/Meta-Llama-3-8B] -svv
```

## Observed Behaviour
> RuntimeError: Unsupported operation for lowering from TTForge to TTIR: pad_tile

## Logs

- [llama3_seq_issue.log](https://github.com/user-attachments/files/17460284/llama3_seq_issue.log)

**Comment by nvukobratTT** [comment]
This pad_tile is an op that we should deprecate. In a few cases, we saw that it appeared as a result of transpose over -3 decomposition. Can you confirm on a few cases if that's correct as well? 

For the mentioned case, @mstojkovicTT is already working on solution :))
