### ISSUE TITLE
RuntimeError: Unhandled attribute type 

### ISSUE THREAD

**Issue by kamalrajkannan78** [tenstorrent/tt-forge-fe#505]
## Description

-  RuntimeError: Unhandled attribute type

## Reproduce

```
git checkout kkannan/forge_model_issues_nov12
git submodule update --recursive
pytest forge/test/model_demos/high_prio/cnn/pytorch/test_ssd300_resnet50.py -svv
```

## Observed Behaviour
```
context = CompileContext(modules=[Module pt_ssd300_resnet50], graph_name='pt_ssd300_resnet50', compiler_cfg=CompilerConfig(enabl...unt=0, target_cycles_offset=0, forge_module=<forge._C.ForgeGraphModule object at 0x7f9f18f196f0>, compiled_binary=None)

    def run_mlir_compiler(context: CompileContext) -> CompileDepth:
        assert context.forge_module is not None
    
>       context.compiled_binary = forge._C.run_mlir_compiler(context.forge_module)
E       RuntimeError: Unhandled attribute type
```

## Logs

- [ssd300_resnet50.log](https://github.com/user-attachments/files/17716212/nov12_ssd300_resnet50_issue.log)

**Comment by ashokkumarkannan1** [comment]
This issue seems resolved now and currently blocked with Unsupported clip op.

### Op Config
```
Found Unsupported operations while lowering from TTForge to TTIR in forward graph
Unsupported Ops at: RUN_MLIR_COMPILER stage
clip
		 Input_shape: [{2, 1, 7, 7}, ]
					 Attributes: clip{max: 1.000000e+00, min: 0.000000e+00}
```

[clip.log](https://github.com/user-attachments/files/17630023/clip.log)

**Comment by nvukobratTT** [comment]
Good, I assume we can close up this issue?

**Comment by ashokkumarkannan1** [comment]
yes @nvukobratTT 

Compile Depth for this clip model is changed to SPLIT_GRAPH in this patch. https://github.com/tenstorrent/tt-forge-fe/pull/636

**Comment by ashokkumarkannan1** [comment]
@kamalrajkannan78  Can you update the reproduce step in Description for models you faced this issue here?

**Comment by kamalrajkannan78** [comment]
description updated now with repro steps @ashokkumarkannan1
