### ISSUE TITLE
[Llama 3.2 1B] - Add specific op tests

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-forge-fe#533]
## Summary
To confirm that each op individually works for the Llama model, let's add a set of op tests that are specific to this variation of the Llama model. 

To do so, here are a few hints:
1. Print unique ops appearing in Llama. 
    - To do so, use [this](https://docs.tenstorrent.com/tt-forge-fe/tools.html#gather-unique-ops-configuration) feature
1. For each unique op (and related input shape, attribute, etc.) create an e2e op test
    - The recommendation is to keep these model-related op tests as part of the model directory. E.g. `forge/test/mlir/llama/ops/*`
1. Make sure to run e2e tests as further as possible
    - To make this possible, you can use compile depth (e.g. `compiler_cfg.compile_depth = forge.CompileDepth.SPLIT_GRAPH`)

**Comment by mstojkovicTT** [comment]
Additional info for each of the ops that doesnt work:

- add - eltwise binary broadcast not working
- concat - Tile padding along concated dim 3 not supported yet
- sin i cos - waiting MLIR uplift
- embedding - reshape in TILE_LAYOUT
- matmul - doesn’t meet the required pcc score
- multiply - eltwise binary broadcast not working
- reduce_avg - doesn’t meet the required pcc score
- reshape - reshape in TILE_LAYOUT and if dim != 4 is not working
- transpose - seg-fault (double free)
