### ISSUE TITLE
Add Push pytest mark to all push CI tests

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-forge-fe#539]
## Summary
For all tests that are currently run in the push pipeline, let's add the following pytest mark:
```
@pytest.mark.push
```

For more details, check this doc:
- https://docs.pytest.org/en/stable/example/markers.html

**Comment by ashokkumarkannan1** [comment]
Fixed https://github.com/tenstorrent/tt-forge-fe/pull/550
