### ISSUE TITLE
Add Nightly pytest mark to all nightly CI tests

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-forge-fe#540]
## Summary
For all tests that are currently run in the nightly pipeline, let's add the following pytest mark:
```
@pytest.mark.nightly
```

For more details, check this doc:
- https://docs.pytest.org/en/stable/example/markers.html

**Comment by ashokkumarkannan1** [comment]
Fixed https://github.com/tenstorrent/tt-forge-fe/pull/551
