### ISSUE TITLE
Shape mismatch due to invalid erase inverse ops operation

### ISSUE THREAD

**Issue by ashokkumarkannan1** [tenstorrent/tt-forge-fe#546]
Due to invalid transpose op removal in erase inverse ops pass, there is a shape mismatch issue based on invalid commute shape calculation.

Repro steps
```bash
$ git checkout akannan/test_mismatch_sanity
$ git submodule update --init --recursive -f
$ pytest -svv forge/test/model_demos/high_prio/cnn/pytorch/test_shape_mismatch.py::test_wideresnet_pytorch[no_device-wide_resnet50_2]
```

Before Erase Inverse Ops:
![image (4)](https://github.com/user-attachments/assets/50b443fd-e20e-4c37-8aea-df92a2100032)

After Erase Inverse Ops:
![image (5)](https://github.com/user-attachments/assets/8c030858-6bbd-476c-abc2-906170af8202)

**Comment by dgolubovicTT** [comment]
Hey @ashokkumarkannan1, do you have any insights on this one? I am looking into problems with erase inverse ops logic so if you have something interesting, feel free to share.

**Comment by dgolubovicTT** [comment]
I think I have identified the bug. More updates later today...
