### ISSUE TITLE
Tests failin in tt-mlir uplift

### ISSUE THREAD

**Issue by vmilosevic** [tenstorrent/tt-forge-fe#608]
We have test failing when trying to do a tt-mlir [uplift ](https://github.com/tenstorrent/tt-forge-fe/actions/runs/11660305268/job/32462390318 )

```
forge/test/mlir/test_ops.py::test_abs[shape1] 2024-11-04 08:27:35.112 | INFO     | forge.compile:compile_main:219 - Compiling module abs
...
LLVM ERROR: checking for an interface (`mlir::DialectInlinerInterface`) that was promised by dialect 'func' but never implemented. This is generally an indication that the dialect extension implementing the interface was never registered.
```

**Comment by sdjordjevicTT** [comment]
@nvukobratTT @pilkicTT take a look at this:
https://github.com/tenstorrent/tt-mlir/pull/1096#discussion_r1819993436

FYI @LPanosTT

**Comment by pilkicTT** [comment]
@sdjordjevicTT Yeah, I am aware of this; and we already have a fix for the inliner.
