### ISSUE TITLE
Runtime error  : stride mismatch 

### ISSUE THREAD

**Issue by kamalrajkannan78** [tenstorrent/tt-forge-fe#609]
## Description

- Stride mismatch runtime error in wideresnet 

## Reproduce

```
git checkout kkannan/stride_issue
git submodule update --recursive
pytest forge/test/mlir/test_ops.py -k " stride" -svv
```

## Observed Behaviour
> E       RuntimeError: Tensor 1 - stride mismatch: expected [128, 128, 128, 1], got [128, 1, 1, 1]

## Logs

- [wideresnet_stride_issue.log](https://github.com/user-attachments/files/17615850/xx_nov4_stride_s_2.log)

**Comment by nvukobratTT** [comment]
@kamalrajkannan78 this issue is going to be resolved soon (PR is approved and ready to be merged). Once that's done, let's re-check linked models and push them further :))
