### ISSUE TITLE
update Llama 3.2 1B tests

### ISSUE THREAD

**Issue by mstojkovicTT** [tenstorrent/tt-forge-fe#922]
We have updated the requirements file, PR #904, to incorporate newer versions of various modules, including Llama 3.2. Consequently, tests that were previously skipped due to compatibility issues have had their `@pytest.mark.skip` decorators removed.

**Comment by mstojkovicTT** [comment]
Waiting for either a Hugging Face token or storage to save models before removing `pytest.mark.skip`

**Comment by nvukobratTT** [comment]
@mstojkovicTT token should be updated on our CI. Feel free to double-check if it's working now :))
